### ISSUE TITLE
Julia 1.0

### ISSUE THREAD

**Issue by femtotrader** [staticfloat/InfluxDB.jl#2]
Hello,

any chance to have this package for Julia 1.0?
Thanks

Kind regards

**Comment by oschulz** [comment]
@staticfloat , I'd also be interested.

**Comment by staticfloat** [comment]
This package never got very far; that's why it's still unregistered.  If someone else wants to write it, that's fine by me.  If you take a look at the source, you will see that there's almost nothing there, and that updating what is there to 1.0 should take no more than a few minutes.

**Comment by oschulz** [comment]
Thanks for the info! We still have to decide whether we'll go with InfluxDB for a specific system here, but if so, I may be able to pick this up.

**Comment by staticfloat** [comment]
I had a chance to update this package significantly, so I'm going to close this for now.

**Comment by oschulz** [comment]
Thanks, @staticfloat!

Would you consider a new release, so re-enable pkg-add for this package?

**Comment by staticfloat** [comment]
Considering I essentially re-wrote this package over the last couple of hours in a frenzy of activity, there are probably many little bugs hidden inside it not caught by the (admittedly rather light) test suite.

I suggest you play around with it by adding it by URL directly first, and see if it works for you.  You can `pkg> add https://github.com/staticfloat/InfluxDB.jl` to install it directly from within Julia.

**Comment by oschulz** [comment]
Oh, sure, I didn't mean right now. :-) One of our students, @lmh91 had actually gotten it to run on Julia-1
during the last days (https://github.com/lmh91/InfluxDB.jl/tree/julia-v1), he was about to do a PR. ;-)

I'll ask him to check out the new version.

**Comment by baumgold** [comment]
@staticfloat - now that you have re-written this package and it seems to work as expected can it be registered with the General package registry?  Thanks!
